"""Eliminar columna pais sin uso

Revision ID: a66745786946
Revises: 30dcd4d6dfe2
Create Date: 2024-07-04 10:04:21.116073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66745786946'
down_revision: Union[str, None] = '30dcd4d6dfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
